services:
  telco_db:
    image: postgres:latest
    hostname: telco_db
    container_name: telco_db_container
    restart: on-failure
    environment:
      - POSTGRES_DB=telco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cobapassword
    volumes:
      - ./telco_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432 
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge